[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://serpas.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "https://serpas1.onrender.com/socket.io/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://serpas.cloud"
  status = 200
