[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "http://localhost:8000/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "http://localhost:8080/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "http://localhost:3000/:splat"
  status = 200